name: VoiceReminders
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
targets:
  VoiceReminders:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSMicrophoneUsageDescription: "We need access to your microphone to record voice commands for creating reminders."
        NSSpeechRecognitionUsageDescription: "We need speech recognition to convert your voice commands into reminders."
        UIBackgroundModes: [audio]
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1,2
        DEVELOPMENT_TEAM: ""
    dependencies:
      - sdk: Speech.framework
      - sdk: AVFoundation.framework
      - sdk: UserNotifications.framework
  VoiceRemindersTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: Tests/Info.plist
    dependencies:
      - target: VoiceReminders
      - sdk: Speech.framework
      - sdk: AVFoundation.framework 